FROM python:3.9-bullseye AS builder

RUN useradd -ms /bin/bash pythonrunner

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    libpq-dev \
    libxml2

USER pythonrunner

COPY requirements.txt /tmp/requirements.txt

RUN pip3 install -U --no-cache-dir uwsgi pip setuptools wheel
RUN pip3 install --no-cache-dir --user -r /tmp/requirements.txt


FROM builder As dev-container

USER root

COPY requirements.txt /tmp/requirements.txt
RUN cp -r /home/pythonrunner/.local/* /usr/local

WORKDIR /app/oilstubdata
USER pythonrunner

CMD ["bash"]
