version: "3.8"

services:
  backend:
    hostname: backend
    build:
      context: .
      target: prod-container
#    volumes:
#      - ./:/app/:delegated
#      - ./oilstubdata:/app/
#      - ./creds.json:/app/secrets/creds.json
    working_dir: /app
    user: root
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - default

  # The proxy will help us connect to remote CloudSQL instance locally.
  # Make sure to turn off any VPNs for the proxy to work.
  cloud_sql_proxy:
    container_name: cloud_sql_proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    volumes:
      - ./secrets:/secrets/cloudsql/
    command: /cloud_sql_proxy -instances="oilstub-backend1:us-south1:oilstub-db"=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/creds.json

    ports:
      - 127.0.0.1:5432:5432
    restart: always
