from uuid import uuid4

from django.db import models


class TrackModel(models.Model):
    uuid = models.UUIDField(db_index=True, primary_key=True, default=uuid4)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class OgCountyLeaseCycle(TrackModel):
    oil_gas_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=20)
    lease_no = models.CharField(max_length=20)
    cycle_year = models.CharField(max_length=20)
    cycle_month = models.CharField(max_length=20)
    county_no = models.CharField(max_length=20)
    operator_no = models.CharField(max_length=20)
    field_no = models.CharField(max_length=20)
    cycle_year_month = models.CharField(max_length=20)
    field_type = models.CharField(max_length=128)
    gas_well_no = models.CharField(max_length=20)
    prod_report_field_flag = models.CharField(max_length=128)
    cnty_lse_oil_prod_vol = models.CharField(max_length=128)
    cnty_lse_oil_allow = models.CharField(max_length=20)
    cnty_lse_oil_ending_bal = models.CharField(max_length=20)
    cnty_lse_gas_prod_vol = models.CharField(max_length=20)
    cnty_lse_gas_allow = models.CharField(max_length=20)
    cnty_lse_gas_lift_inj_vol = models.CharField(max_length=20)
    cnty_lse_cond_prod_vol = models.CharField(max_length=20)
    cnty_lse_cond_limit = models.CharField(max_length=20)
    cnty_lse_cond_ending_bal = models.CharField(max_length=20)
    cnty_lse_csgd_prod_vol = models.CharField(max_length=20)
    cnty_lse_csgd_limit = models.CharField(max_length=20)
    cnty_lse_csgd_gas_lift = models.CharField(max_length=20)
    cnty_lse_oil_tot_disp = models.CharField(max_length=20)
    cnty_lse_gas_tot_disp = models.CharField(max_length=20)
    cnty_lse_cond_tot_disp = models.CharField(max_length=20)
    cnty_lse_csgd_tot_disp = models.CharField(max_length=20)
    district_name = models.CharField(max_length=128)
    lease_name = models.CharField(max_length=128)
    operator_name = models.CharField(max_length=128)
    field_name = models.CharField(max_length=128)
    county_name = models.CharField(max_length=128)


class GpCounty(TrackModel):
    county_no = models.CharField(max_length=20)
    district_name = models.CharField(max_length=128)
    county_name = models.CharField(max_length=128)
    county_fips_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=128)
    on_shore_flag = models.CharField(max_length=20)
    onshore_assc_cnty_flag = models.CharField(max_length=20)


class GpDateRangeCycle(TrackModel):
    oldest_prod_cycle_year_month = models.CharField(max_length=20)
    newest_prod_cycle_year_month = models.CharField(max_length=20)
    newest_sched_cycle_year_month = models.CharField(max_length=20)
    gas_extract_date = models.CharField(max_length=128)
    oil_extract_date = models.CharField(max_length=128)


class GpDistrict(TrackModel):
    district_no = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    office_phone_no = models.CharField(max_length=20)
    office_location = models.CharField(max_length=128)


class OgCountyCycle(TrackModel):
    county_no = models.CharField(max_length=128)
    district_no = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    cycle_year = models.CharField(max_length=128)
    cycle_month = models.CharField(max_length=128)
    cycle_year_month = models.CharField(max_length=128)
    cnty_oil_prod_vol = models.CharField(max_length=128)
    cnty_oil_allow = models.CharField(max_length=128)
    cnty_oil_ending_bal = models.CharField(max_length=128)
    cnty_gas_prod_vol = models.CharField(max_length=128)
    cnty_gas_allow = models.CharField(max_length=128)
    cnty_gas_lift_inj_vol = models.CharField(max_length=128)
    cnty_cond_prod_vol = models.CharField(max_length=128)
    cnty_cond_limit = models.CharField(max_length=128)
    cnty_cond_ending_bal = models.CharField(max_length=128)
    cnty_csgd_prod_vol = models.CharField(max_length=128)
    cnty_csgd_limit = models.CharField(max_length=128)
    cnty_csgd_gas_lift = models.CharField(max_length=128)
    cnty_oil_tot_disp = models.CharField(max_length=128)
    cnty_gas_tot_disp = models.CharField(max_length=128)
    cnty_cond_tot_disp = models.CharField(max_length=128)
    cnty_csgd_tot_disp = models.CharField(max_length=128)
    county_name = models.CharField(max_length=128)
    oil_gas_code = models.CharField(max_length=128)


class OgDistrictCycle(TrackModel):
    district_no = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    cycle_year = models.CharField(max_length=128)
    cycle_month = models.CharField(max_length=128)
    cycle_year_month = models.CharField(max_length=128)
    dist_oil_prod_vol = models.CharField(max_length=128)
    dist_gas_prod_vol = models.CharField(max_length=128)
    dist_cond_prod_vol = models.CharField(max_length=128)
    dist_csgd_prod_vol = models.CharField(max_length=128)


class OgFieldCycle(TrackModel):
    field_no = models.CharField(max_length=128)
    field_name = models.CharField(max_length=128)
    district_no = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    cycle_year = models.CharField(max_length=20)
    cycle_month = models.CharField(max_length=20)
    cycle_year_month = models.CharField(max_length=20)
    field_oil_prod_vol = models.CharField(max_length=20)
    field_gas_prod_vol = models.CharField(max_length=20)
    field_cond_prod_vol = models.CharField(max_length=20)
    field_csgd_prod_vol = models.CharField(max_length=20)


class OgFieldDw(TrackModel):
    field_no = models.CharField(max_length=20)
    field_name = models.CharField(max_length=128)
    district_no = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    field_class = models.CharField(max_length=128)
    field_h2s_flag = models.CharField(max_length=128)
    field_manual_rev_flag = models.CharField(max_length=128)
    wildcat_flag = models.CharField(max_length=128)
    o_derived_rule_type_code = models.CharField(max_length=128)
    g_derived_rule_type_code = models.CharField(max_length=128)
    o_rescind_dt = models.CharField(max_length=128)
    g_rescind_dt = models.CharField(max_length=128)
    o_salt_dome_flag = models.CharField(max_length=128)
    g_salt_dome_flag = models.CharField(max_length=128)
    o_offshore_code = models.CharField(max_length=128)
    g_offshore_code = models.CharField(max_length=128)
    o_dont_permit = models.CharField(max_length=128)
    g_dont_permit = models.CharField(max_length=128)
    o_noa_man_rev_rule = models.CharField(max_length=128)
    g_noa_man_rev_rule = models.CharField(max_length=128)
    o_county_no = models.CharField(max_length=128)
    g_county_no = models.CharField(max_length=128)
    o_discovery_dt = models.CharField(max_length=128)
    g_discovery_dt = models.CharField(max_length=128)
    o_sched_remarks = models.CharField(max_length=128)
    g_sched_remarks = models.CharField(max_length=128)
    o_comments = models.CharField(max_length=128)
    g_comments = models.CharField(max_length=128)
    create_by = models.CharField(max_length=128)
    create_dt = models.CharField(max_length=120)
    modify_by = models.CharField(max_length=128)
    modify_dt = models.CharField(max_length=120)


class OgLeaseCycle(TrackModel):
    oil_gas_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=128)
    lease_no = models.CharField(max_length=128)
    operator_no = models.CharField(max_length=128)
    field_no = models.CharField(max_length=128)
    cycle_year_month_min = models.CharField(max_length=128)
    cycle_year_month_max = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    lease_name = models.CharField(max_length=128)
    operator_name = models.CharField(max_length=128)
    field_name = models.CharField(max_length=128)


class OgLeaseCycleDisp(TrackModel):
    oil_gas_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=128)
    lease_no = models.CharField(max_length=128)
    operator_no = models.CharField(max_length=128)
    field_no = models.CharField(max_length=128)
    cycle_year = models.CharField(max_length=128)
    cycle_month = models.CharField(max_length=128)
    cycle_year_month = models.CharField(max_length=128)
    lease_oil_dispcd00_vol = models.CharField(max_length=128)
    lease_oil_dispcd01_vol = models.CharField(max_length=128)
    lease_oil_dispcd02_vol = models.CharField(max_length=128)
    lease_oil_dispcd03_vol = models.CharField(max_length=128)
    lease_oil_dispcd04_vol = models.CharField(max_length=128)
    lease_oil_dispcd05_vol = models.CharField(max_length=128)
    lease_oil_dispcd06_vol = models.CharField(max_length=128)
    lease_oil_dispcd07_vol = models.CharField(max_length=128)
    lease_oil_dispcd09_vol = models.CharField(max_length=128)
    lease_oil_dispcd99_vol = models.CharField(max_length=128)
    lease_gas_dispcd01_vol = models.CharField(max_length=128)
    lease_gas_dispcd02_vol = models.CharField(max_length=128)
    lease_gas_dispcd03_vol = models.CharField(max_length=128)
    lease_gas_dispcd04_vol = models.CharField(max_length=128)
    lease_gas_dispcd05_vol = models.CharField(max_length=128)
    lease_gas_dispcd06_vol = models.CharField(max_length=128)
    lease_gas_dispcd07_vol = models.CharField(max_length=128)
    lease_gas_dispcd08_vol = models.CharField(max_length=128)
    lease_gas_dispcd09_vol = models.CharField(max_length=128)
    lease_gas_dispcd99_vol = models.CharField(max_length=128)
    lease_cond_dispcd00_vol = models.CharField(max_length=128)
    lease_cond_dispcd01_vol = models.CharField(max_length=128)
    lease_cond_dispcd02_vol = models.CharField(max_length=128)
    lease_cond_dispcd03_vol = models.CharField(max_length=128)
    lease_cond_dispcd04_vol = models.CharField(max_length=128)
    lease_cond_dispcd05_vol = models.CharField(max_length=128)
    lease_cond_dispcd06_vol = models.CharField(max_length=128)
    lease_cond_dispcd07_vol = models.CharField(max_length=128)
    lease_cond_dispcd08_vol = models.CharField(max_length=128)
    lease_cond_dispcd09_vol = models.CharField(max_length=128)
    lease_cond_dispcd99_vol = models.CharField(max_length=128)
    lease_csgd_dispcd01_vol = models.CharField(max_length=128)
    lease_csgd_dispcd02_vol = models.CharField(max_length=128)
    lease_csgd_dispcd03_vol = models.CharField(max_length=128)
    lease_csgd_dispcd04_vol = models.CharField(max_length=128)
    lease_csgd_dispcd05_vol = models.CharField(max_length=128)
    lease_csgd_dispcd06_vol = models.CharField(max_length=128)
    lease_csgd_dispcd07_vol = models.CharField(max_length=128)
    lease_csgd_dispcd08_vol = models.CharField(max_length=128)
    lease_csgd_dispcd09_vol = models.CharField(max_length=128)
    lease_csgd_dispcd99_vol = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    lease_name = models.CharField(max_length=128)
    operator_name = models.CharField(max_length=128)
    field_name = models.CharField(max_length=128)


class OgOperatorCycle(TrackModel):
    operator_no = models.CharField(max_length=128)
    cycle_year = models.CharField(max_length=128)
    cycle_month = models.CharField(max_length=128)
    cycle_year_month = models.CharField(max_length=128)
    operator_name = models.CharField(max_length=128)
    oper_oil_prod_vol = models.CharField(max_length=128)
    oper_gas_prod_vol = models.CharField(max_length=128)
    oper_cond_prod_vol = models.CharField(max_length=128)
    oper_csgd_prod_vol = models.CharField(max_length=128)


class OgOperatorDw(TrackModel):
        operator_no = models.CharField(max_length=128)
        operator_name = models.CharField(max_length=128)
        p5_status_code = models.CharField(max_length=128)
        p5_last_filed_dt = models.CharField(max_length=128)
        operator_tax_cert_flag = models.CharField(max_length=128)
        operator_sb639_flag = models.CharField(max_length=128)
        fa_option_code = models.CharField(max_length=128)
        record_status_code = models.CharField(max_length=128)
        efile_status_code = models.CharField(max_length=128)
        efile_effective_dt = models.CharField(max_length=128)
        create_by = models.CharField(max_length=128)
        create_dt = models.CharField(max_length=120)
        modify_by = models.CharField(max_length=128)
        modify_dt = models.CharField(max_length=120)


class OgRegulatoryLeaseDw(TrackModel):
    oil_gas_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=128)
    lease_no = models.CharField(max_length=128)
    operator_no = models.CharField(max_length=128)
    field_no = models.CharField(max_length=128)
    field_name = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    lease_name = models.CharField(max_length=128)
    operator_name = models.CharField(max_length=128)
    well_no = models.CharField(max_length=128)
    lease_off_sched_flag = models.CharField(max_length=128)
    lease_severance_flag = models.CharField(max_length=128)


class OgSummaryMasterLarge(TrackModel):
    oil_gas_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=128)
    lease_no = models.CharField(max_length=128)
    operator_no = models.CharField(max_length=128)
    field_no = models.CharField(max_length=128)
    field_name = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    lease_name = models.CharField(max_length=128)
    operator_name = models.CharField(max_length=128)
    cycle_year_month_min = models.CharField(max_length=128)
    cycle_year_month_max = models.CharField(max_length=128)


class OgSummaryOnShoreLease(TrackModel):
    oil_gas_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=128)
    lease_no = models.CharField(max_length=128)
    operator_no = models.CharField(max_length=128)
    field_no = models.CharField(max_length=128)
    field_name = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    lease_name = models.CharField(max_length=128)
    operator_name = models.CharField(max_length=128)
    cycle_year_month_min = models.CharField(max_length=128)
    cycle_year_month_max = models.CharField(max_length=128)


class OgWellCompletion(TrackModel):
    oil_gas_code = models.CharField(max_length=20)
    district_no = models.CharField(max_length=128)
    lease_no = models.CharField(max_length=128)
    well_no = models.CharField(max_length=128)
    district_name = models.CharField(max_length=128)
    county_name = models.CharField(max_length=128)
    api_county_code = models.CharField(max_length=128)
    api_unique_no = models.CharField(max_length=128)
    onshore_assc_cnty = models.CharField(max_length=128)
    oil_well_unit_no = models.CharField(max_length=128)
    well_root_no = models.CharField(max_length=128)
    wellbore_shutin_dt = models.CharField(max_length=128)
    well_shutin_dt = models.CharField(max_length=128)
    well_14b2_status_code = models.CharField(max_length=128)
    well_subject_14b2_flag = models.CharField(max_length=128)
    wellbore_location_code = models.CharField(max_length=128)
