# Generated by Django 4.1.5 on 2023-01-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilandgasdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpcountydata',
            old_name='onshore_assc_cnty_flas',
            new_name='onshore_assc_cnty_flag',
        ),
    ]
