# Generated by Django 4.1.5 on 2023-01-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilandgasdata', '0002_rename_onshore_assc_cnty_flas_gpcountydata_onshore_assc_cnty_flag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GpDataRangeCycle',
            new_name='GpDateRangeCycleData',
        ),
    ]
