# Generated by Django 4.1.5 on 2023-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilandgasdata', '0003_rename_gpdatarangecycle_gpdaterangecycledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpdaterangecycledata',
            name='gas_extract_date',
            field=models.DateField(default='17-DEC-22'),
        ),
        migrations.AlterField(
            model_name='gpdaterangecycledata',
            name='oil_extract_date',
            field=models.DateField(default='17-DEC-22'),
        ),
    ]
