# Generated by Django 4.1.5 on 2023-01-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilandgasdata', '0004_alter_gpdaterangecycledata_gas_extract_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpdaterangecycledata',
            name='gas_extract_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gpdaterangecycledata',
            name='oil_extract_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ogfielddwdata',
            name='create_dt',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ogfielddwdata',
            name='modify_dt',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ogoperatordwdata',
            name='create_dt',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ogoperatordwdata',
            name='modify_dt',
            field=models.CharField(max_length=120),
        ),
    ]
