# Generated by Django 4.1.5 on 2023-01-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilandgasdata', '0005_alter_gpdaterangecycledata_gas_extract_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GpDistrict',
            new_name='GpDistrictData',
        ),
    ]
