# Generated by Django 4.1.5 on 2023-01-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilandgasdata', '0006_rename_gpdistrict_gpdistrictdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpdistrictdata',
            old_name='office_phone',
            new_name='office_phone_no',
        ),
    ]
